#!/usr/bin/env bash
# Configure Nginx server so that /redirect_me is redirecting to another page.
sudo apt-get update
sudo apt-get -y install nginx
# Firewall port 80
sudo ufw allow http
# opcional para que el echo de index tenga permisos y funcione
sudo chgrp -R ubuntu /usr/share/nginx/html
sudo chmod -R g+w /usr/share/nginx/html
# Index
# Ubuntu 14 /usr/share/nginx/html/index.html
# ubuntu 16 /var/www/html/index.html
echo "Holberton School" > /var/www/html/index.html
# Redirection
sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
# start server
service nginx start
