#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header
# Comments on --> 0x0C-web_server/4-not_found_page_404
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow http
sudo chgrp -R ubuntu /usr/share/nginx/html
sudo chmod -R g+w /usr/share/nginx/html
echo "Holberton School" > /var/www/html/index.html
sudo echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/custom_404.html
sed -i "/listen 80 default_server/a add_header X-Served-By \"$HOSTNAME\";" /etc/nginx/sites-available/default
sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sed -i '/listen 80 default_server/a error_page 404 /custom_404.html; location = /custom_404.html {root /usr/share/nginx/html;\n internal;}' /etc/nginx/sites-available/default
service nginx start
