#!/usr/bin/env bash
# Install and configure HAproxy on your load balancer server

sudo apt-get -y update
sudo apt-get install -y haproxy
config=\
"
frontend  web-frontend
        bind *:80
        mode http
        default_backend web-backend
backend web-backend
        balance roundrobin
        server 65918-web-01 34.203.33.229:80 check
        server 65918-web-02 54.237.66.163:80 check
"
echo "$config" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo service haproxy restart
